### ISSUE TITLE
Can't use grid with huge datasets

### ISSUE THREAD

**Issue by bendecoste** [OpenMined/Grid#10]
Even the full mnist set fails (all 60000 images)

**Comment by bendecoste** [comment]
This would probably start to fail in training because it will try to load the entire set into memory

**Comment by jvmancuso** [comment]
Shouldn't it be fairly straightforward to split into batches and train on each batch in sequence?  Thinking client identifies the batch, sends a piece of each batch to the workers, training happens for a full pass, then the client sends an interrupt signal followed by the next batch.
