### ISSUE TITLE
Installation and Dependency Management

### ISSUE THREAD

**Issue by ianlivingstone** [OpenMined/Grid#106]
@jvmancuso brought up a good point in my pull request #102 

> Question -- is there a way to automatically install the correct version of torch based on CUDA version? I'm really not sure, but if installing torch from requirements.txt will automatically install the CPU version, and we want to use a version compiled for CUDA, we may want to have the user do this on their own and add that to the install instructions.
> 
> Right now, this isn't a huge issue, because torch is only imported for certain prototypes, but I'm currently working on a pretty big PR that's going to make PyTorch the main interface for Grid.

I thought I'd open an issue for discussion purposes to start figuring out how to handle these dependencies. Ideally, there'd be a single line or two to run as a developer to setup (e.g. `python setup.py install`) your development environment.

Then, conda, pip wheels, and binaries could be packaged for distribution on release, similar to pytorch or other libraries.

In terms of installing torch, a part of the setup script could detect whether or not a system dependency is missing and prompt them to install, or ask if they wish to use it?

In terms of the installer, it'd probably be best to be as smart as possible about what's available on the system and the context of the installation (e.g. cuda support available) and then taking advantage of it optimistically.

Thoughts?

**Comment by iamtrask** [comment]
I'm a huge fan of this idea - but I don't quite know where to begin. So far I've just been writing basic installation scripts in bash which are by no means robust. Are there any tools you can recommend for making this easier?.. or are we still talking about a big (smart) bash script at the end of the day?

**Comment by bendecoste** [comment]
could create developer and user friendly scripts with something like http://www.fabfile.org/

**Comment by justin1121** [comment]
I vote for creating wheels!

**Comment by ianlivingstone** [comment]
There are a couple of different options, depending on the audience we're talking about. 

For development, we could use a tool like [`conda`](https://conda.io/docs/) (packaged with Annaconda) for managing system dependencies and package management. We can also look into using pip wheels, but there are some limitations that'll require a bit of thought. Conda does a bit more than pip wheels out of the box as it also handles managing python versions etc.

While for consumers (miners, etc), we could build a CI/CD pipeline that results in a packaged installer which would do much of the same thing creating a binary that a system could use to install the required dependencies and install openmined. This one is a bit trickier, because it's platform dependent, but I've had a lot of success supporting apt/yum/brew, etc. and offering windows installers for distributing releases.

**Comment by justin1121** [comment]
Found lots of interesting information in here: https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/

It sort of convinced me that conda might be the better choice since we are using a pretty big stack with ipfs, go etc. Apparently conda can handle packaging those things whereas pip cannot.

**Comment by ianlivingstone** [comment]
> Found lots of interesting information in here: https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/

This is actually the same article I was reading the other day.

> It sort of convinced me that conda might be the better choice since we are using a pretty big stack with ipfs, go etc. Apparently conda can handle packaging those things whereas pip cannot.

This is what [pytorch](https://github.com/pytorch/pytorch#from-source) does as well, but they require you to install cuda components as well. Using conda might be a good first step, but having a full fledged story for intelligently detecting support and install the necessary optimizations would be a good goal from a user convenience perspective.
