### ISSUE TITLE
move `pretty_print` functions out of client/grid

### ISSUE THREAD

**Issue by bendecoste** [OpenMined/Grid#109]
There are a few utility functions to print stuff near the bottom of client/grid.  These should likely be in a utility class.

**Comment by vbawa** [comment]
Hello, I was looking through the "good first issue" label and this seems like a simple one to use for an end-o-end of the contribution process.  Per the OpenMined contributing guidelines, I wasn't clear on whether I need to "claim" the issue or just create a PR for it, but I figured better safe than sorry.
