### ISSUE TITLE
Automate contributing guidelines at bottom of README

### ISSUE THREAD

**Issue by justin1121** [OpenMined/Grid#139]
I've added some contributing guidelines at the bottom of the README on how to make sure your code is good before sending a PR. It would be good if these steps were made automatic.

**Comment by ppirrip** [comment]
is a simple shell script, e.g. ./run_test, executing the 4 steps (including pip install) outlined in the README what you are looking for, at least on unix side?

**Comment by ianlivingstone** [comment]
It'd be nice if we had a build script, or Makefile (whichever is the Python equivalent), then this could be leveraged in CI and locally by developers.
