### ISSUE TITLE
Create unit tests for existing code

### ISSUE THREAD

**Issue by justin1121** [OpenMined/Grid#141]
Right now a lot of code isn't covered by unit tests. This is an open-ended issue where you can create your own project by decided to write some unit tests to cover an area of code you're interested in. Just create a file with your tests in the tests directory. These tests can then be run by running `pytest`.

**Comment by ucalyptus** [comment]
Can I take this up?I'm a newbie.

**Comment by robert-wagner** [comment]
Absolutely! If you want help figuring out where to start let me know.

**Comment by jvmancuso** [comment]
@ucalyptus dude yes please!!
