### ISSUE TITLE
Dockerize Python Grid Edge Nodes

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/Grid#16]
For both improved security and convenience, we need the ability for people to simply download a docker image for a Grid node - with that image automagically running the appropriate IPFS server and grid worker daemon.

Acceptance Criteria
- automatically builds from master branch
- runs IPFS server
- runs daemon
- ships with dependencies
- can run on linux, windows, and mac (tested)
- automatically attaches to NVIDIA GPUs for all 3 major frameworks (keras, pytorch, tensorflow) (tested) (https://github.com/NVIDIA/nvidia-docker)

**Comment by bendecoste** [comment]
i can look into this if no one else has started

**Comment by bendecoste** [comment]
nvm I think @robert-wagner is looking into it

**Comment by ppirrip** [comment]
submitted https://github.com/OpenMined/Grid/pull/127 for ubuntu 16.04 docker

**Comment by robert-wagner** [comment]
@ppirrip, is that pr supposed to contain no changes?

**Comment by ppirrip** [comment]
@robert-wagner no changes as is final? I have a feeling a few adjustment will be needed like by passing the email/user info and reduce duplicated from the ubuntu_installation script etc. Is there an existing docker file somewhere? Maybe I missed it in the master branch.

**Comment by robert-wagner** [comment]
@ppirrip no changes as in when I look at the pr it has 0 additions and 0 deletions. Definitely work needs to be done. There should be a preliminary docker/docker compose file on my branch but those aren't done because I got distracted by mpc stuff

**Comment by ppirrip** [comment]
Yup, looks like I lost the PR (and the dockerfile) for some reason. Will do another one. Strange
