### ISSUE TITLE
Slices of slices of Tensors aren't being registered.

### ISSUE THREAD

**Issue by jvmancuso** [OpenMined/Grid#171]
When iterating over a slice of a tensor, the new chunks aren't registered.  So far, the only known problem with this is that printing large tensors raises an AttributeError, although there are likely other bugs that result that we just don't know about yet.

Code to reproduce: `print(torch.FloatTensor(128,128))`.

**Comment by robert-wagner** [comment]
How does this compare to pure pytorch

**Comment by jvmancuso** [comment]
Normally, when you do this in pure PyTorch, it will show you a condensed string representation of the tensor (with ellipses in between the first few and last few rows/columns).  The code that constructs that string representation is what's breaking.
