### ISSUE TITLE
printing network_stats problem

### ISSUE THREAD

**Issue by AnantachokD** [OpenMined/Grid#187]
From the picture, I was connected to IPFS, and found 2 openmined nodes. client.get_openmined_nodes() showed the 2 nodes, but client.print_network_stats() printed nothing.
I also tried to print each client by a for loop, 
for x in client :
    print(x)
and it didn't print any node.
Jason suggested that it might be some bugs from `refresh_network_stats` in `BaseClient`.
 
![screenshot from 2018-05-23 02-26-03](https://user-images.githubusercontent.com/25325441/40399558-f3ea026a-5e35-11e8-89c5-43bbe830bbd8.png)

**Comment by jvmancuso** [comment]
@iamtrask what's strange about this is that it works for the rest of us, but not @AnantachokD.  Curiously, he was able to call `client.get_openmined_nodes()` and it would return other nodes on the network (excluding his own local worker), so it's probably not a firewall thing.

**Comment by ccthien** [comment]
Me got the same...
![untitled](https://user-images.githubusercontent.com/1134300/41427200-38754ae6-7017-11e8-8241-2c0350ba36d6.png)

**Comment by ccthien** [comment]
When I call:
client.refresh_network_stats()

It get stuck forever on this request:
=================================================
---- _request get
++++ url http://127.0.0.1:5001/api/v0/pubsub/sub
++++ params [('stream-channels', 'true'), ('arg', 'client:QmZYUVEHVpwjztazBndyChpMQQXC6VX4PTYTjnscWvxZyQ_6388677842'), ('arg', False)]
++++ parser <grid.ipfsapi.encoding.Json object at 0x7f8a15010b38>
++++ stream True
res <Response [200]>

at "def stream_decode(): for data in res:" - http.py

**Comment by ccthien** [comment]
I already tried with:

One anchor: QmZrSZA6VyRPUiBvVrmtyRzaDgpZJKDgwnQ2GdbiYZzEUT
One compute: QmasvFyh34n5NqwENnNcqRguR6bkrcNttTRxQQyZFntWBG

TouchClient found all 3:

ret {'Strings': ['QmXkWUybbTnfvFH8SUcrug6RGTLYTB23gSockKLxueR1vQ', 'QmZrSZA6VyRPUiBvVrmtyRzaDgpZJKDgwnQ2GdbiYZzEUT', 'QmasvFyh34n5NqwENnNcqRguR6bkrcNttTRxQQyZFntWBG']}
UPDATE: Searching for IPFS nodes - 41 found overall - 3 are OpenMined workers          

SUCCESS: Found 3 OpenMined nodes!!!

------------------------------------------------------
But print_network_stats still return None:

print(client.get_openmined_nodes())
['QmXkWUybbTnfvFH8SUcrug6RGTLYTB23gSockKLxueR1vQ', 'QmZrSZA6VyRPUiBvVrmtyRzaDgpZJKDgwnQ2GdbiYZzEUT', 'QmasvFyh34n5NqwENnNcqRguR6bkrcNttTRxQQyZFntWBG']

print(client.print_network_stats())
None

**Comment by ccthien** [comment]
for your more information, I print some debug on compute PC and get this:

data b'{"from":"EiA+g+1rb3emRVlbqFPXN/9ejH7pZNhvktoTxIhrhpQ1Sg==","data":"eyJ0b3JjaF90eXBlIjogInRvcmNoLmF1dG9ncmFkLnZhcmlhYmxlLlZhcmlhY'
data b'mxlIiwgInJlcXVpcmVzX2dyYWQiOiB0cnVlLCAidm9sYXRpbGUiOiBmYWxzZSwgImRhdGEiOiAie1widG9yY2hfdHlwZVwiOiBcInRvcmNoLkZsb2F0VGVuc29yXCIsI'
data b'FwiZGF0YVwiOiBbWzAuMDE2ODU3NzE5MDQ4ODU3NjldLCBbLTAuMTQ4ODc5ODU1ODcxMjAwNTZdLCBbLTAuMjAzMDkxMDcwMDU1OTYxNl0sIFswLjE4MjMzMzMwNTQ3O'
data b'DA5Nl0sIFswLjA5NzA2MTg0MjY3OTk3NzQyXSwgWy0wLjEzNzAwNjMxMjYwODcxODg3XSwgWzAuMzEwMDY5NDcxNTk3NjcxNV0sIFstMC4xNzI3NDAzOTk4Mzc0OTM5X'
data b'SwgWy0wLjAxNzYxOTQyMzU2ODI0ODc1XSwgWy0wLjQwMDc5MjY1ODMyOTAxXSwgWzAuMTA1MTY3NTA4MTI1MzA1MThdLCBbMC4zMTgyNjEwMjczMzYxMjA2XSwgWy0wL'
data b'jA5NzE3NTk0MDg3MTIzODcxXSwgWy0wLjE0NzYyMTgxMDQzNjI0ODc4XSwgWy0wLjA4Nzc4NjAwMzk0NzI1OF0sIFstMC4wNTIyMjA0MTE1OTg2ODI0MDRdLCBbLTAuM'
data b'jM4OTE3NjE4OTg5OTQ0NDZdLCBbMC4yMTYwMjgzMTc4MDkxMDQ5Ml0sIFstMC4xODUwOTgzOTQ3NTE1NDg3N10sIFstMC4wMjMwNTk5MDY0Mzc5OTMwNV0sIFstMC4zN'
data b'jIwMTI1OTQ5MzgyNzgyXSwgWy0wLjIyMTIxMTc0NjMzNTAyOTZdLCBbLTAuNDg1NTc4NjU2MTk2NTk0MjRdLCBbMC4yMjQxMTY0Mjk2ODY1NDYzM10sIFswLjIxOTAxN'
data b'zkzNzc3OTQyNjU3XSwgWy0wLjM3NTg0ODgyOTc0NjI0NjM0XSwgWy0wLjM5NjY2NjU4NjM5OTA3ODM3XSwgWy0wLjExMDk0Njk3NTY0ODQwMzE3XSwgWy0wLjAxNTM3M'
data b'zI5NzAzNTY5NDEyMl0sIFstMC4zMTQ5MTQ2NDM3NjQ0OTU4NV0sIFstMC4xMjg1NjU1NDk4NTA0NjM4N10sIFswLjEzOTIzMDI1MTMxMjI1NTg2XV0sIFwiaWRcIjogN'
data b'TQ3NjE5Nzc5OSwgXCJvd25lcnNcIjogW1wiY29tcHV0ZTpRbWFzdkZ5aDM0bjVOcXdFTm5OY3FSZ3VSNmJrcmNOdHRUUnhRUXlaRm50V0JHXCJdLCBcImlzX3BvaW50Z'
data b'XJcIjogZmFsc2V9IiwgImdyYWQiOiBudWxsLCAiaWQiOiA1MDkxNTY0OTcxLCAib3duZXJzIjogWyJjb21wdXRlOlFtYXN2RnloMzRuNU5xd0VObk5jcVJndVI2YmtyY'
data b'050dFRSeFFReVpGbnRXQkciXSwgImlzX3BvaW50ZXIiOiBmYWxzZX0=","seqno":"FTkCLTm4sJg=","topicIDs":["openmined:torch_listen_for_obj:comp'
data b'ute:QmasvFyh34n5NqwENnNcqRguR6bkrcNttTRxQQyZFntWBG"]}\n'

May be someone else can connect to my compute PC?

**Comment by ccthien** [comment]
I think I found the issue

base_worker.py --> listen_to_channel_impl
for m in new_messages: --> the init_func on this loop and it never call because there is no message come before init

I move the init_func to out side of the loop

```
        if init_function is not None and first_proc:
           init_function()
           first_proc = False
        for m in new_messages:
           message = self.decode_message(m)
           if message is not None:
               fr = base58.encode(message['from'])
               if not ignore_from_self or fr != self.id:
                   out = handle_message(message)
                   if out is not None:
                       return out
               else:
                   print('ignore mssage from self')
```

and it make print_network_stats work:
ANCHOR - 2 - NAME:Thien  Ping:0.04sec  CPUs:2  CPU Load:0.0  Disk-util:7.0%  RAM-util:22.5%  GPUs:[]
COMPUTE - 3 - NAME:Thien  Ping:0.06sec  CPUs:2  CPU Load:17.9  Disk-util:7.0%  RAM-util:23.7%  GPUs:[]

I do not know why that init_func is putted in side the loop...
