### ISSUE TITLE
AttributeError: 'function' object has no attribute 'Variable'

### ISSUE THREAD

**Issue by ccthien** [OpenMined/Grid#189]
AttributeError                            Traceback (most recent call last)
<ipython-input-2-77162589207e> in <module>()
      3 import torch.nn as nn
      4 from torch.autograd import Variable
----> 5 from grid.clients.torch import TorchClient
      6 import numpy as np
      7 import re

~/OpenMined/Grid/grid/__init__.py in <module>()
----> 1 from . import clients
      2 from .channels import torch_listen_for_obj_callback

~/OpenMined/Grid/grid/clients/__init__.py in <module>()
----> 1 from . import base
      2 from . import keras
      3 from . import torch

~/OpenMined/Grid/grid/clients/base.py in <module>()
----> 1 from ..workers import base_worker
      2 from .. import channels
      3 from grid.lib import utils
      4 from .pretty_printer import PrettyPrinter
      5 

~/OpenMined/Grid/grid/workers/__init__.py in <module>()
      1 from . import *
----> 2 from . import compute
      3 from . import tree
      4 from . import anchor

~/OpenMined/Grid/grid/workers/compute.py in <module>()
----> 1 from . import base_worker
      2 from ..lib import strings, utils, output_pipe
      3 from .. import channels
      4 from ..services.fit_worker import FitWorkerService
      5 from ..services.listen_for_openmined_nodes import ListenForOpenMinedNodesService

~/OpenMined/Grid/grid/workers/base_worker.py in <module>()
      9 from ..lib import utils
     10 from ..services.broadcast_known_workers import BroadcastKnownWorkersService
---> 11 from ..services.whoami import WhoamiService
     12 
     13 

~/OpenMined/Grid/grid/services/__init__.py in <module>()
      4 from . import listen_for_openmined_nodes
      5 from . import broadcast_known_workers
----> 6 from . import torch

~/OpenMined/Grid/grid/services/torch/__init__.py in <module>()
----> 1 from . import torch_service

~/OpenMined/Grid/grid/services/torch/torch_service.py in <module>()
      1 from ..base import BaseService
----> 2 from .hook_service import HookService
      3 from ... import channels
      4 from ...lib import utils,torch_utils as tu
      5 

~/OpenMined/Grid/grid/services/torch/hook_service.py in <module>()
      2 from ..base import BaseService
      3 from ... import channels
----> 4 from ...lib import utils, torch_utils as tu
      5 
      6 from collections import OrderedDict

~/OpenMined/Grid/grid/lib/torch_utils.py in <module>()
     95 }
     96 map_var_type = {
---> 97     'torch.autograd.variable.Variable':torch.autograd.variable.Variable,
     98     'torch.nn.parameter.Parameter':torch.nn.parameter.Parameter
     99 }

**Comment by jvmancuso** [comment]
Hi, this is a copy of OpenMined/PySyft#1336.  You can check out the response there, and feel free to reach out with any further questions here!
