### ISSUE TITLE
Problem to reproduce Grid Example

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/Grid#196]
I had some problems reproducing the example guide.
1 - `git clone git@github.com:OpenMined/Grid.git` **(step 5)** command returns a denied permission message
     - Solution 1 : change to `git clone git@github.com/OpenMined/Grid.git` at grid/__ init __.py file (line 140)
      - Solution 2 : Add instruction to use github ssh key

Lib versions:
grid==0.1.0a1
syft==0.1.13a1
pytorch==1.0.1

**Comment by mari-linhares** [comment]
+1
