### ISSUE TITLE
Error when running: pip install -r app/requirements.txt

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/Grid#197]
> ERROR: syft 0.1.13a1 has requirement torch==1.0.1, but you'll have torch 1.0.1.post2 which is incompatible.

Maybe remove torch from requirements since it will be installed by syft?

**Comment by iamtrask** [comment]
I think that should work, yes.

**Comment by mari-linhares** [comment]
No longer relevant :woman_cartwheeling:
