### ISSUE TITLE
Grid Nodes Which Can Communicate With Each Other

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/Grid#200]
We need Grid nodes to be able to communicate with each other like they do in PySyft. In this issue, we need to add an extra endpoint to Grid nodes which allow one node to tell another node that it exists (and to create a Pointer locally).

Acceptance Criteria:
- a client should be able to call x.move(another_worker) and send a tensor from one Heroku based worker to another Heroku based worker.

**Comment by jopasserat** [comment]
still very early at this stage but might be useful (see Peer Discovery entry, especially DHT) 
https://github.com/libp2p/py-libp2p
