### ISSUE TITLE
Hosting a Model on a Grid Worker

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/Grid#204]
Part of Epic: #203 
--
As a part of the EMLaaS Epic (#203), we want to be able to host models on grid workers such that they can be queried for various processes (such as training or prediction). This issue is just concerned with the hosting.

Acceptance Criteria:
1) we should be able to spin up a heroku worker with an example model already hosted
2) we should be able to query the heroku worker for what models it has using a grid client. Something like 

```grid_client.models``` should return a list of pointers to the grid models contained on the worker the grid_client points to. 

3) each model should have a unique ID as metadata
4) models should be stored in the virtual_worker._objects dictionary.

**Comment by mari-linhares** [comment]
I think we need generic pointers (https://github.com/OpenMined/PySyft/pull/2096) to create a pointer to the models.

**Comment by mari-linhares** [comment]
We also need a way to serialize a model using plans.

**Comment by mari-linhares** [comment]
Generic pointers now are a reality in PySyft, also now we have a way to serialize/deserialize pytorch models using jit module. No blockers, I'm on it :woman_cartwheeling:
