### ISSUE TITLE
TypeError: launch_on_heroku() missing 1 required positional argument: 'app_type'

### ISSUE THREAD

**Issue by amit-rastogi** [OpenMined/Grid#238]
While calling the following api as given in "Part 1: Launch a Grid Node on Heroku.ipynb"

GridClient(addr=gr.launch_on_heroku("opengrid10", verbose=True, check_deps=True)) 

got the error ->
TypeError: launch_on_heroku() missing 1 required positional argument: 'app_type'

What should be passed to the launch_on_heroku() api in 'app_type' parameter?

**Comment by mari-linhares** [comment]
Thanks for reporting the issue @amit-rastogi, it should be fixed soon.
