### ISSUE TITLE
AttributeError: module 'grid' has no attribute 'launch_on_heroku'

### ISSUE THREAD

**Issue by Polarbeargo** [OpenMined/Grid#241]
Hello all,

I'm running the [Launch_Websocket_Grid_worker.ipynb](https://github.com/OpenMined/Grid/blob/dev/examples/experimental/Launch_Websocket_Grid_worker.ipynb) but encounter "AttributeError: module 'grid' has no attribute 'launch_on_heroku'" like below screenshots after I install syft and grid:
![1](https://user-images.githubusercontent.com/8589224/59557597-413e7700-9010-11e9-952b-d4878557c408.png)
![2](https://user-images.githubusercontent.com/8589224/59557599-44396780-9010-11e9-8366-a2bba108a5da.png)
Any guidance will be very appreciated :)!
Environment: Google Colab

**Comment by mari-linhares** [comment]
Hey @Polarbeargo,

Can you run these commands and tell me the output?

```python
import grid
help(grid)
```

**Comment by Polarbeargo** [comment]
Thank you mari-linhares. Yes, I can 😊. I will update in here as soon as I got home very appreciate your guidance:).

**Comment by Polarbeargo** [comment]
Hello @mari-linhares the attached screenshot is the output.
![3](https://user-images.githubusercontent.com/8589224/59560279-f0e00d00-9041-11e9-85f9-514427396792.png)

**Comment by mari-linhares** [comment]
I think you don't have the right version of grid installed.

I've added some steps (first cells) in [this Colab](https://gist.github.com/mari-linhares/d14f03b8702a3d5632102239f2e924fc) to use the most updated version of Grid (the one on the dev branch).

Can you try it?

I'll close this issue for now, but please let me know if you face any other problems :blush: !

**Comment by Polarbeargo** [comment]
@mari-linhares thank you! I'll work on it 😊!
