### ISSUE TITLE
tensor.share implementation

### ISSUE THREAD

**Issue by mari-linhares** [OpenMined/Grid#253]
`tensor.share` should work with grid workers in order to have #240

**Comment by mari-linhares** [comment]
I think this can be closed, right? Do we have tests for it? @IonesioJunior

**Comment by IonesioJunior** [comment]
Yep! We have tests for it.
https://github.com/OpenMined/Grid/blob/9885bfac7c7a8d481db3d1ed5e8f1b628d0501b2/test/test_api_socketio.py#L166-L171
