### ISSUE TITLE
Drop out of training if you don't think you'll finish first

### ISSUE THREAD

**Issue by bendecoste** [OpenMined/Grid#29]
We need a mechanism to quit training a model if the trainer doesn't think it will finish first.

For example, if Alice is running a worker node on her macbook air and Bob is running a node on his gaming computer, Bob will probably train any model faster.  Both Alice & Bob should publish their progress as they go so Alice will know that she is not going to win and can give up.  She would know this when Bob tells her he is 50% done and she is only 5% done.  She can then try to pick up work while she is idle again and Bob is still working.

We should do this issue first and then use it in conjunction to make a very slick system to complete #28.

**Comment by bendecoste** [comment]
I'll do this

**Comment by cereallarceny** [comment]
This is also in line with the designs that have been created.  Theoretically, a user should always have the ability to pause or stop the training of a model for whatever reason.

Thanks for doing this @bendecoste - let me know if you need any visual assistance.

**Comment by jvmancuso** [comment]
What happens to the user's portion of the data if a user quits???  Wouldn't we be training an incomplete model?
