### ISSUE TITLE
Implement Torch Grid and Client Notebook

### ISSUE THREAD

**Issue by mjvypr** [OpenMined/Grid#59]
Like the Keras notebook, implement one for PyTorch:
https://github.com/OpenMined/Grid/blob/master/notebooks/pubsub/Keras%20Grid%20Client%20and%20Worker.ipynb

TODO

- [ ] Implement fit, serialize and deserialize support for torch.
- [ ]  Create a python notebook that works like the one for Keras

**Comment by mjvypr** [comment]
Starting Work: https://github.com/OpenMined/Grid/pull/58

**Comment by jvmancuso** [comment]
Heads up -- new strategy for this has begun in #84.
